### PR TITLE
Support of PHP54 - get_class(X) instead of X::class

### LINKED ISSUE #3: PHP 5.4?
The bundle's composer.json says that the code only works in PHP 5.5+. Is this really the case that it cannot be ran on 5.4 for some objective reason? Not much changed between these versions, if I am not wrong.

It would be good if you changed composer.json to support PHP 5.4 (if that wont break anything, of course).

### PR DESCRIPTION
**Pull request by kachkaev**
Should fix #3

### CODE REVIEW

**Comment by jjsaunier** [comment]
I will check it tonight, thank you @kachkaev

**Comment by jjsaunier** [comment]
This is not working on my side. I got `[Symfony\Component\Debug\Exception\ContextErrorException]                      
  Notice: Use of undefined constant RouteCollection - assumed 'RouteCollection'`   for each replacement.

**Comment by jjsaunier** [comment]
I close this PR in favor of 514d007470e7f357a5c648ee248503158a4ede78. I have replace get_class(CLASS) with FQCN and remove test to rewrite them with phpspec (they are currently broken and unmaintanable).

Thank you.

**Comment by kachkaev** [comment]
Cool, thanks Johann!

**Pull request closed without merging**
